// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDocument(arg1) {
  return window['go']['handlers']['DocumentHandler']['CreateDocument'](arg1);
}

export function DeleteDocument(arg1) {
  return window['go']['handlers']['DocumentHandler']['DeleteDocument'](arg1);
}

export function GetDocumentList() {
  return window['go']['handlers']['DocumentHandler']['GetDocumentList']();
}

export function LoadDocumentContent(arg1) {
  return window['go']['handlers']['DocumentHandler']['LoadDocumentContent'](arg1);
}

export function RenameDocument(arg1, arg2) {
  return window['go']['handlers']['DocumentHandler']['RenameDocument'](arg1, arg2);
}

export function ReorderDocuments(arg1) {
  return window['go']['handlers']['DocumentHandler']['ReorderDocuments'](arg1);
}

export function SaveDocumentContent(arg1, arg2) {
  return window['go']['handlers']['DocumentHandler']['SaveDocumentContent'](arg1, arg2);
}

export function SetActiveDocument(arg1) {
  return window['go']['handlers']['DocumentHandler']['SetActiveDocument'](arg1);
}
