// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {document} from '../models';

export function CreateDocument(arg1:string):Promise<document.Meta>;

export function DeleteDocument(arg1:string):Promise<void>;

export function GetDocumentList():Promise<document.Index>;

export function LoadDocumentContent(arg1:string):Promise<string>;

export function RenameDocument(arg1:string,arg2:string):Promise<void>;

export function ReorderDocuments(arg1:Array<string>):Promise<void>;

export function SaveDocumentContent(arg1:string,arg2:string):Promise<void>;

export function SetActiveDocument(arg1:string):Promise<void>;
