// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {opengraph} from '../models';
import {markdown} from '../models';
import {handlers} from '../models';
import {context} from '../models';

export function CopyImageToClipboard(arg1:string):Promise<void>;

export function ExportHTMLFile(arg1:string,arg2:string):Promise<void>;

export function ExportMarkdownFile(arg1:string,arg2:string):Promise<void>;

export function FetchLinkMetadata(arg1:string):Promise<opengraph.LinkMetadata>;

export function ImportMarkdownFile():Promise<markdown.ImportResult>;

export function LoadExternalFile(arg1:string):Promise<string>;

export function OpenExternalFile():Promise<handlers.ExternalFile>;

export function PrintHTML(arg1:string,arg2:string):Promise<void>;

export function SaveExternalFile(arg1:string,arg2:string):Promise<void>;

export function SaveImage(arg1:string,arg2:string):Promise<string>;

export function SaveImageFile(arg1:string,arg2:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;
