// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyImageToClipboard(arg1) {
  return window['go']['handlers']['FileHandler']['CopyImageToClipboard'](arg1);
}

export function ExportHTMLFile(arg1, arg2) {
  return window['go']['handlers']['FileHandler']['ExportHTMLFile'](arg1, arg2);
}

export function ExportMarkdownFile(arg1, arg2) {
  return window['go']['handlers']['FileHandler']['ExportMarkdownFile'](arg1, arg2);
}

export function FetchLinkMetadata(arg1) {
  return window['go']['handlers']['FileHandler']['FetchLinkMetadata'](arg1);
}

export function ImportMarkdownFile() {
  return window['go']['handlers']['FileHandler']['ImportMarkdownFile']();
}

export function LoadExternalFile(arg1) {
  return window['go']['handlers']['FileHandler']['LoadExternalFile'](arg1);
}

export function OpenExternalFile() {
  return window['go']['handlers']['FileHandler']['OpenExternalFile']();
}

export function PrintHTML(arg1, arg2) {
  return window['go']['handlers']['FileHandler']['PrintHTML'](arg1, arg2);
}

export function SaveExternalFile(arg1, arg2) {
  return window['go']['handlers']['FileHandler']['SaveExternalFile'](arg1, arg2);
}

export function SaveImage(arg1, arg2) {
  return window['go']['handlers']['FileHandler']['SaveImage'](arg1, arg2);
}

export function SaveImageFile(arg1, arg2) {
  return window['go']['handlers']['FileHandler']['SaveImageFile'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['handlers']['FileHandler']['SetContext'](arg1);
}
