// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRAGConfig() {
  return window['go']['handlers']['RAGHandler']['GetRAGConfig']();
}

export function GetRAGStatus() {
  return window['go']['handlers']['RAGHandler']['GetRAGStatus']();
}

export function IndexBookmarkContent(arg1, arg2, arg3) {
  return window['go']['handlers']['RAGHandler']['IndexBookmarkContent'](arg1, arg2, arg3);
}

export function RebuildIndex() {
  return window['go']['handlers']['RAGHandler']['RebuildIndex']();
}

export function SaveRAGConfig(arg1) {
  return window['go']['handlers']['RAGHandler']['SaveRAGConfig'](arg1);
}
