// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';

export function GetRAGConfig():Promise<handlers.EmbeddingConfig>;

export function GetRAGStatus():Promise<handlers.RAGStatus>;

export function IndexBookmarkContent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RebuildIndex():Promise<number>;

export function SaveRAGConfig(arg1:handlers.EmbeddingConfig):Promise<void>;
