// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SearchDocuments(arg1) {
  return window['go']['handlers']['SearchHandler']['SearchDocuments'](arg1);
}

export function SemanticSearch(arg1, arg2) {
  return window['go']['handlers']['SearchHandler']['SemanticSearch'](arg1, arg2);
}

export function SemanticSearchDocuments(arg1, arg2) {
  return window['go']['handlers']['SearchHandler']['SemanticSearchDocuments'](arg1, arg2);
}
