// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';

export function SearchDocuments(arg1:string):Promise<Array<handlers.SearchResult>>;

export function SemanticSearch(arg1:string,arg2:number):Promise<Array<handlers.SemanticSearchResult>>;

export function SemanticSearchDocuments(arg1:string,arg2:number):Promise<Array<handlers.DocumentSearchResult>>;
