// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';

export function GetSettings():Promise<handlers.Settings>;

export function SaveSettings(arg1:handlers.Settings):Promise<void>;
