// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDocumentTag(arg1, arg2) {
  return window['go']['handlers']['TagHandler']['AddDocumentTag'](arg1, arg2);
}

export function CreateTagGroup(arg1) {
  return window['go']['handlers']['TagHandler']['CreateTagGroup'](arg1);
}

export function DeleteTagGroup(arg1) {
  return window['go']['handlers']['TagHandler']['DeleteTagGroup'](arg1);
}

export function GetAllTags() {
  return window['go']['handlers']['TagHandler']['GetAllTags']();
}

export function GetTagColors() {
  return window['go']['handlers']['TagHandler']['GetTagColors']();
}

export function GetTagGroups() {
  return window['go']['handlers']['TagHandler']['GetTagGroups']();
}

export function RemoveDocumentTag(arg1, arg2) {
  return window['go']['handlers']['TagHandler']['RemoveDocumentTag'](arg1, arg2);
}

export function RenameTagGroup(arg1, arg2) {
  return window['go']['handlers']['TagHandler']['RenameTagGroup'](arg1, arg2);
}

export function ReorderTagGroups(arg1) {
  return window['go']['handlers']['TagHandler']['ReorderTagGroups'](arg1);
}

export function SetTagColor(arg1, arg2) {
  return window['go']['handlers']['TagHandler']['SetTagColor'](arg1, arg2);
}

export function SetTagGroupCollapsed(arg1, arg2) {
  return window['go']['handlers']['TagHandler']['SetTagGroupCollapsed'](arg1, arg2);
}
