// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';

export function AddDocumentTag(arg1:string,arg2:string):Promise<void>;

export function CreateTagGroup(arg1:string):Promise<void>;

export function DeleteTagGroup(arg1:string):Promise<void>;

export function GetAllTags():Promise<Array<handlers.TagInfo>>;

export function GetTagColors():Promise<Record<string, string>>;

export function GetTagGroups():Promise<Array<handlers.TagInfo>>;

export function RemoveDocumentTag(arg1:string,arg2:string):Promise<void>;

export function RenameTagGroup(arg1:string,arg2:string):Promise<void>;

export function ReorderTagGroups(arg1:Array<string>):Promise<void>;

export function SetTagColor(arg1:string,arg2:string):Promise<void>;

export function SetTagGroupCollapsed(arg1:string,arg2:boolean):Promise<void>;
