// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyImageToClipboard(arg1) {
  return window['go']['main']['App']['CopyImageToClipboard'](arg1);
}

export function CreateDocument(arg1) {
  return window['go']['main']['App']['CreateDocument'](arg1);
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function DeleteDocument(arg1) {
  return window['go']['main']['App']['DeleteDocument'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function ExportMarkdownFile(arg1, arg2) {
  return window['go']['main']['App']['ExportMarkdownFile'](arg1, arg2);
}

export function GetDocumentList() {
  return window['go']['main']['App']['GetDocumentList']();
}

export function GetFolders() {
  return window['go']['main']['App']['GetFolders']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportMarkdownFile() {
  return window['go']['main']['App']['ImportMarkdownFile']();
}

export function LoadDocumentContent(arg1) {
  return window['go']['main']['App']['LoadDocumentContent'](arg1);
}

export function LoadExternalFile(arg1) {
  return window['go']['main']['App']['LoadExternalFile'](arg1);
}

export function MoveDocumentToFolder(arg1, arg2) {
  return window['go']['main']['App']['MoveDocumentToFolder'](arg1, arg2);
}

export function OpenExternalFile() {
  return window['go']['main']['App']['OpenExternalFile']();
}

export function RenameDocument(arg1, arg2) {
  return window['go']['main']['App']['RenameDocument'](arg1, arg2);
}

export function RenameFolder(arg1, arg2) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2);
}

export function ReorderDocuments(arg1) {
  return window['go']['main']['App']['ReorderDocuments'](arg1);
}

export function ReorderFolders(arg1) {
  return window['go']['main']['App']['ReorderFolders'](arg1);
}

export function SaveDocumentContent(arg1, arg2) {
  return window['go']['main']['App']['SaveDocumentContent'](arg1, arg2);
}

export function SaveExternalFile(arg1, arg2) {
  return window['go']['main']['App']['SaveExternalFile'](arg1, arg2);
}

export function SaveImage(arg1, arg2) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchDocuments(arg1) {
  return window['go']['main']['App']['SearchDocuments'](arg1);
}

export function SetActiveDocument(arg1) {
  return window['go']['main']['App']['SetActiveDocument'](arg1);
}

export function SetFolderCollapsed(arg1, arg2) {
  return window['go']['main']['App']['SetFolderCollapsed'](arg1, arg2);
}
