// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {document} from '../models';
import {folder} from '../models';
import {main} from '../models';
import {markdown} from '../models';

export function Cleanup():Promise<void>;

export function CopyImageToClipboard(arg1:string):Promise<void>;

export function CreateDocument(arg1:string):Promise<document.Meta>;

export function CreateFolder(arg1:string):Promise<folder.Folder>;

export function DeleteDocument(arg1:string):Promise<void>;

export function DeleteFolder(arg1:string):Promise<void>;

export function ExportHTMLFile(arg1:string,arg2:string):Promise<void>;

export function ExportMarkdownFile(arg1:string,arg2:string):Promise<void>;

export function GetDocumentList():Promise<document.Index>;

export function GetFolders():Promise<Array<folder.Folder>>;

export function GetSettings():Promise<main.Settings>;

export function ImportMarkdownFile():Promise<markdown.ImportResult>;

export function LoadDocumentContent(arg1:string):Promise<string>;

export function LoadExternalFile(arg1:string):Promise<string>;

export function MoveDocumentToFolder(arg1:string,arg2:string):Promise<void>;

export function OpenExternalFile():Promise<main.ExternalFile>;

export function PrintHTML(arg1:string,arg2:string):Promise<void>;

export function RenameDocument(arg1:string,arg2:string):Promise<void>;

export function RenameFolder(arg1:string,arg2:string):Promise<void>;

export function ReorderDocuments(arg1:Array<string>):Promise<void>;

export function ReorderFolders(arg1:Array<string>):Promise<void>;

export function SaveDocumentContent(arg1:string,arg2:string):Promise<void>;

export function SaveExternalFile(arg1:string,arg2:string):Promise<void>;

export function SaveImage(arg1:string,arg2:string):Promise<string>;

export function SaveImageFile(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SearchDocuments(arg1:string):Promise<Array<main.SearchResult>>;

export function SetActiveDocument(arg1:string):Promise<void>;

export function SetFolderCollapsed(arg1:string,arg2:boolean):Promise<void>;
