// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDocumentTag(arg1, arg2) {
  return window['go']['main']['App']['AddDocumentTag'](arg1, arg2);
}

export function Cleanup() {
  return window['go']['main']['App']['Cleanup']();
}

export function CopyImageToClipboard(arg1) {
  return window['go']['main']['App']['CopyImageToClipboard'](arg1);
}

export function CreateDocument(arg1) {
  return window['go']['main']['App']['CreateDocument'](arg1);
}

export function DeleteDocument(arg1) {
  return window['go']['main']['App']['DeleteDocument'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function ExportHTMLFile(arg1, arg2) {
  return window['go']['main']['App']['ExportHTMLFile'](arg1, arg2);
}

export function ExportMarkdownFile(arg1, arg2) {
  return window['go']['main']['App']['ExportMarkdownFile'](arg1, arg2);
}

export function FetchLinkMetadata(arg1) {
  return window['go']['main']['App']['FetchLinkMetadata'](arg1);
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetDocumentGraph(arg1) {
  return window['go']['main']['App']['GetDocumentGraph'](arg1);
}

export function GetDocumentList() {
  return window['go']['main']['App']['GetDocumentList']();
}

export function GetExternalBlockContent(arg1, arg2) {
  return window['go']['main']['App']['GetExternalBlockContent'](arg1, arg2);
}

export function GetMCPInfo() {
  return window['go']['main']['App']['GetMCPInfo']();
}

export function GetOS() {
  return window['go']['main']['App']['GetOS']();
}

export function GetPinnedTags() {
  return window['go']['main']['App']['GetPinnedTags']();
}

export function GetRAGConfig() {
  return window['go']['main']['App']['GetRAGConfig']();
}

export function GetRAGStatus() {
  return window['go']['main']['App']['GetRAGStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTagColors() {
  return window['go']['main']['App']['GetTagColors']();
}

export function ImportMarkdownFile() {
  return window['go']['main']['App']['ImportMarkdownFile']();
}

export function IndexBookmarkContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['IndexBookmarkContent'](arg1, arg2, arg3);
}

export function IndexFileContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['IndexFileContent'](arg1, arg2, arg3);
}

export function IndexFolderContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['IndexFolderContent'](arg1, arg2, arg3);
}

export function LoadDocumentContent(arg1) {
  return window['go']['main']['App']['LoadDocumentContent'](arg1);
}

export function LoadExternalFile(arg1) {
  return window['go']['main']['App']['LoadExternalFile'](arg1);
}

export function OpenExternalFile() {
  return window['go']['main']['App']['OpenExternalFile']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenFileWithSystem(arg1) {
  return window['go']['main']['App']['OpenFileWithSystem'](arg1);
}

export function PinTag(arg1) {
  return window['go']['main']['App']['PinTag'](arg1);
}

export function PrintHTML(arg1, arg2) {
  return window['go']['main']['App']['PrintHTML'](arg1, arg2);
}

export function RebuildIndex() {
  return window['go']['main']['App']['RebuildIndex']();
}

export function RemoveDocumentTag(arg1, arg2) {
  return window['go']['main']['App']['RemoveDocumentTag'](arg1, arg2);
}

export function RenameDocument(arg1, arg2) {
  return window['go']['main']['App']['RenameDocument'](arg1, arg2);
}

export function RenameTag(arg1, arg2) {
  return window['go']['main']['App']['RenameTag'](arg1, arg2);
}

export function ReorderDocuments(arg1) {
  return window['go']['main']['App']['ReorderDocuments'](arg1);
}

export function ReorderPinnedTags(arg1) {
  return window['go']['main']['App']['ReorderPinnedTags'](arg1);
}

export function RevealInFinder(arg1) {
  return window['go']['main']['App']['RevealInFinder'](arg1);
}

export function SaveDocumentContent(arg1, arg2) {
  return window['go']['main']['App']['SaveDocumentContent'](arg1, arg2);
}

export function SaveExternalFile(arg1, arg2) {
  return window['go']['main']['App']['SaveExternalFile'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveImage(arg1, arg2) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2);
}

export function SaveImageFile(arg1, arg2) {
  return window['go']['main']['App']['SaveImageFile'](arg1, arg2);
}

export function SaveRAGConfig(arg1) {
  return window['go']['main']['App']['SaveRAGConfig'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchDocuments(arg1) {
  return window['go']['main']['App']['SearchDocuments'](arg1);
}

export function SelectFolderDialog() {
  return window['go']['main']['App']['SelectFolderDialog']();
}

export function SemanticSearchDocuments(arg1, arg2, arg3) {
  return window['go']['main']['App']['SemanticSearchDocuments'](arg1, arg2, arg3);
}

export function SetActiveDocument(arg1) {
  return window['go']['main']['App']['SetActiveDocument'](arg1);
}

export function SetPinnedTagCollapsed(arg1, arg2) {
  return window['go']['main']['App']['SetPinnedTagCollapsed'](arg1, arg2);
}

export function SetTagColor(arg1, arg2) {
  return window['go']['main']['App']['SetTagColor'](arg1, arg2);
}

export function UnpinTag(arg1) {
  return window['go']['main']['App']['UnpinTag'](arg1);
}
