// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDocumentTag(arg1, arg2) {
  return window['go']['main']['App']['AddDocumentTag'](arg1, arg2);
}

export function Cleanup() {
  return window['go']['main']['App']['Cleanup']();
}

export function CopyImageToClipboard(arg1) {
  return window['go']['main']['App']['CopyImageToClipboard'](arg1);
}

export function CreateDocument(arg1) {
  return window['go']['main']['App']['CreateDocument'](arg1);
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function CreateTagGroup(arg1) {
  return window['go']['main']['App']['CreateTagGroup'](arg1);
}

export function DeleteDocument(arg1) {
  return window['go']['main']['App']['DeleteDocument'](arg1);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeleteTagGroup(arg1) {
  return window['go']['main']['App']['DeleteTagGroup'](arg1);
}

export function ExportHTMLFile(arg1, arg2) {
  return window['go']['main']['App']['ExportHTMLFile'](arg1, arg2);
}

export function ExportMarkdownFile(arg1, arg2) {
  return window['go']['main']['App']['ExportMarkdownFile'](arg1, arg2);
}

export function FetchLinkMetadata(arg1) {
  return window['go']['main']['App']['FetchLinkMetadata'](arg1);
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetDocumentList() {
  return window['go']['main']['App']['GetDocumentList']();
}

export function GetFolders() {
  return window['go']['main']['App']['GetFolders']();
}

export function GetRAGConfig() {
  return window['go']['main']['App']['GetRAGConfig']();
}

export function GetRAGStatus() {
  return window['go']['main']['App']['GetRAGStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTagColors() {
  return window['go']['main']['App']['GetTagColors']();
}

export function GetTagGroups() {
  return window['go']['main']['App']['GetTagGroups']();
}

export function ImportMarkdownFile() {
  return window['go']['main']['App']['ImportMarkdownFile']();
}

export function LoadDocumentContent(arg1) {
  return window['go']['main']['App']['LoadDocumentContent'](arg1);
}

export function LoadExternalFile(arg1) {
  return window['go']['main']['App']['LoadExternalFile'](arg1);
}

export function MoveDocumentToFolder(arg1, arg2) {
  return window['go']['main']['App']['MoveDocumentToFolder'](arg1, arg2);
}

export function OpenExternalFile() {
  return window['go']['main']['App']['OpenExternalFile']();
}

export function PrintHTML(arg1, arg2) {
  return window['go']['main']['App']['PrintHTML'](arg1, arg2);
}

export function RebuildIndex() {
  return window['go']['main']['App']['RebuildIndex']();
}

export function RemoveDocumentTag(arg1, arg2) {
  return window['go']['main']['App']['RemoveDocumentTag'](arg1, arg2);
}

export function RenameDocument(arg1, arg2) {
  return window['go']['main']['App']['RenameDocument'](arg1, arg2);
}

export function RenameFolder(arg1, arg2) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2);
}

export function RenameTagGroup(arg1, arg2) {
  return window['go']['main']['App']['RenameTagGroup'](arg1, arg2);
}

export function ReorderDocuments(arg1) {
  return window['go']['main']['App']['ReorderDocuments'](arg1);
}

export function ReorderFolders(arg1) {
  return window['go']['main']['App']['ReorderFolders'](arg1);
}

export function ReorderTagGroups(arg1) {
  return window['go']['main']['App']['ReorderTagGroups'](arg1);
}

export function SaveDocumentContent(arg1, arg2) {
  return window['go']['main']['App']['SaveDocumentContent'](arg1, arg2);
}

export function SaveExternalFile(arg1, arg2) {
  return window['go']['main']['App']['SaveExternalFile'](arg1, arg2);
}

export function SaveImage(arg1, arg2) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2);
}

export function SaveImageFile(arg1, arg2) {
  return window['go']['main']['App']['SaveImageFile'](arg1, arg2);
}

export function SaveRAGConfig(arg1) {
  return window['go']['main']['App']['SaveRAGConfig'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchDocuments(arg1) {
  return window['go']['main']['App']['SearchDocuments'](arg1);
}

export function SemanticSearch(arg1, arg2) {
  return window['go']['main']['App']['SemanticSearch'](arg1, arg2);
}

export function SemanticSearchDocuments(arg1, arg2) {
  return window['go']['main']['App']['SemanticSearchDocuments'](arg1, arg2);
}

export function SetActiveDocument(arg1) {
  return window['go']['main']['App']['SetActiveDocument'](arg1);
}

export function SetFolderCollapsed(arg1, arg2) {
  return window['go']['main']['App']['SetFolderCollapsed'](arg1, arg2);
}

export function SetTagColor(arg1, arg2) {
  return window['go']['main']['App']['SetTagColor'](arg1, arg2);
}

export function SetTagGroupCollapsed(arg1, arg2) {
  return window['go']['main']['App']['SetTagGroupCollapsed'](arg1, arg2);
}
